name: Track Merges from Main to Beta

on:
  pull_request:
    types:
      - closed
    branches:
      - beta  

jobs:
  track_changes:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch both main and beta branches explicitly
        run: |
          git fetch origin main
          git fetch origin beta

      - name: Get the merge base between main and beta
        run: |
          BASE_SHA=$(git merge-base origin/main origin/beta)
          if [ -z "$BASE_SHA" ]; then
            echo "Error: No merge base found between main and beta."
            exit 1
          fi
          echo "BASE_SHA=$BASE_SHA" >> $GITHUB_ENV

      - name: Get list of commits merged into beta
        run: |
          echo "Using Base SHA: $BASE_SHA"
          COMMITS=$(git log --oneline $BASE_SHA..origin/beta)
          if [ -z "$COMMITS" ]; then
            echo "No new commits found to track."
            exit 0
          fi
          echo "Commits to be tracked:"
          echo "$COMMITS"
          echo "COMMITS<<EOF" >> $GITHUB_ENV
          echo "$COMMITS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Get merged PRs into beta and format
        run: |
          RAW_PRS=$(gh pr list --base beta --state merged --json title,url -L 100)
          FORMATTED_PRS=$(echo "$RAW_PRS" | jq -r '.[] | "- [\(.title)](\(.url))"')
          echo "Formatted PRs:"
          echo "$FORMATTED_PRS"
          echo "PRS<<EOF" >> $GITHUB_ENV
          echo "$FORMATTED_PRS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create an Issue with the list of commits and PRs
        run: |
          ISSUE_TITLE="Changes Merged from Main to Beta"
          ISSUE_BODY="### Commits Merged
          \n\n$COMMITS\n\n### Merged PRs\n\n$PRS"
          gh issue create --title "$ISSUE_TITLE" --body "$ISSUE_BODY"
